[package]
name = "stackswap-coroutines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
setjmp = "0.1.4"

# [profile.release]
# opt-level = 0
